name: Release Go binaries

on:
  release:
    types: [created]

# set variables
env:
  MYAPP: gnme-theme-manager

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build for Linux
        run: |
          go build -o ${MYAPP} -ldflags="-s -w" -v -tags fyne -ldflags="-H windowsgui" GOOS=linux GOARCH=386
          tar -czf ${MYAPP}-386.tar.gz ${MYAPP}
          go build -o ${MYAPP} -ldflags="-s -w" -v -tags fyne -ldflags="-H windowsgui" GOOS=linux GOARCH=amd64
          tar -czf ${MYAPP}-amd64.tar.gz ${MYAPP}
          go build -o ${MYAPP} -ldflags="-s -w" -v -tags fyne -ldflags="-H windowsgui" GOOS=linux GOARCH=arm64
          tar -czf ${MYAPP}-arm64.tar.gz ${MYAPP}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: Release v1.0
          draft: false
          prerelease: false
          files: |
            ${MYAPP}-386.tar.gz
            ${MYAPP}-amd64.tar.gz
            ${MYAPP}-arm64.tar.gz
